### ISSUE TITLE
Holding on writer file in cals

### ISSUE THREAD

**Issue by dieris** [BBN-Q/Auspex#48] opened 2017-01-27 21:48 UTC
Still happening occasionally. Even after closing and killing the file at the end of an experiment!

**Comment by blakejohnson** [comment] 2017-01-31 17:08
Seems to be caused by h5py/h5py#775. Will be fixed with h5py 2.7.0 is released.

**Comment by dieris** [comment] 2017-01-31 19:21
Replacing data writers with data buffers as @grahamrow suggested may be enough for now. I'd prefer not to save calibration data anyway

**Comment by grahamrow** [comment] 2017-01-31 22:53
We went with DataBuffers for the time being. Merged into master.

**Closed by grahamrow** 2017-01-31 22:53 UTC
Labels: bug
