### ISSUE TITLE
New run never started for last point in sweep range

### ISSUE THREAD

**Issue by appwagner** [BBN-Q/Auspex#52] opened 2017-01-30 23:22 UTC
Setting Temperature to: 6.0 K
Temperature Stablized at 6.088 K
auspex-DEBUG: 2017-01-30 17:56:35,504 ----> Starting a new run.
Measuring ...
auspex-DEBUG: 2017-01-30 17:57:02,231 ----> Sweeper updates values.
auspex-DEBUG: 2017-01-30 17:57:02,251 ----> Sweep Axis 'temp_set' at step 1 takes value: 16.
Setting Temperature to: 16.0 K
Temperature Stablized at 15.999 K
auspex-DEBUG: 2017-01-30 18:07:56,593 ----> Refining on axis temp_set
auspex-DEBUG: 2017-01-30 18:07:56,593 ----> WriteToHDF5 "None" received 4 points
auspex-DEBUG: 2017-01-30 18:07:56,643 ----> Now has 4 of 8 points.
auspex-DEBUG: 2017-01-30 18:07:56,653 ----> HDF5: Write index at 4
auspex-DEBUG: 2017-01-30 18:07:56,653 ----> HDF5: temp_meas_TO_sink has written 4 points
.
.
.
  File "Tc_Measurement_DMM.py", line 303, in transition
    newpoints = refine_1D(points, mean, all_points=False, criterion="difference", threshold = "one_sigma", resolution = TRES, noise_level = RNOISE)
  File "c:\users\qlab\documents\github\adapt\src\adapt\refine.py", line 95, in refine_1D
    fs_sorted = values[sort_inds]
TypeError: only integer arrays with one element can be converted to an index

It seems that new runs are never started for the last point in a sweep axis range. As seen in the debug messages above when two temperature points are given in a sweep, the refine axis method is called immediately after the second point is set and no data is taken for that point.  Eventually this causes the refine function to fail since only one data point was taken.

**Comment by grahamrow** [comment] 2017-01-31 04:08
I think I already closed this out with #51. Let me know if the problem persists. The cause was `push()` not getting called before the `refine_func` being called.

**Closed by grahamrow** 2017-01-31 04:08 UTC
